image: atlassian/default-image:2
pipelines:
  default:
      - step:
          script:
            - git config --global --unset https.proxy
            - git push --force https://dachenej:${BitBucketToken}@bitbucket.org/erp-praktikum/rap-handson-travel-docs.git
            - echo "Repository has been successfully synchronized."